spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/online_shop
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: Jktu310590

logging:
  level:
    root: error
    com.naidiuk.onlineshop.controller: info
  file:
    name: logs/online_shop.log
  pattern:
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"