spring:
  profiles.active: dev
  jpa:
    show-sql: true

nbu:
  rates:
    json-url: https://bank.gov.ua/NBUStatService/v1/statdirectory/exchange?json
    xml-url: https://bank.gov.ua/NBUStatService/v1/statdirectory/exchange

jwt:
  authorization-header: Authorization